package mappers

import (
	"invest-mate/internal/api/dto"
	"invest-mate/internal/models"
)

func BondFromDTO(dto dto.BondDTO) models.Bond {
	return models.Bond{
		Figi:                  dto.Figi,
		Ticker:                dto.Ticker,
		PositionUid:           dto.PositionUid,
		ClassCode:             dto.ClassCode,
		Isin:                  dto.Isin,
		Lot:                   dto.Lot,
		Currency:              dto.Currency,
		Klong:                 dto.Klong.ToFloat(),
		Kshort:                dto.Kshort.ToFloat(),
		Dlong:                 dto.Dlong.ToFloat(),
		Dshort:                dto.Dshort.ToFloat(),
		DlongMin:              dto.DlongMin.ToFloat(),
		DshortMin:             dto.DshortMin.ToFloat(),
		Exchange:              dto.Exchange,
		RealExchange:          dto.RealExchange,
		ShortEnabledFlag:      dto.ShortEnabledFlag,
		Name:                  dto.Name,
		CountryOfRiskName:     dto.CountryOfRiskName,
		TradingStatus:         dto.TradingStatus,
		OtcFlag:               dto.OtcFlag,
		BuyAvailableFlag:      dto.BuyAvailableFlag,
		SellAvailableFlag:     dto.SellAvailableFlag,
		MinPriceIncrement:     dto.MinPriceIncrement.ToFloat(),
		ApiTradeAvailableFlag: dto.ApiTradeAvailableFlag,
		Uid:                   dto.Uid,
		AssetUid:              dto.AssetUid,
		ForIisFlag:            dto.ForIisFlag,
		ForQualInvestorFlag:   dto.ForQualInvestorFlag,
		WeekendFlag:           dto.WeekendFlag,
		BlockedTcaFlag:        dto.BlockedTcaFlag,
		LiquidityFlag:         dto.LiquidityFlag,
		First1minCandleDate:   dto.First1minCandleDate,
		First1dayCandleDate:   dto.First1dayCandleDate,
		AciValue:              dto.AciValue.ToFloat(),
		AmortizationFlag:      dto.AmortizationFlag,
		CountryOfRisk:         dto.CountryOfRisk,
		CouponQuantityPerYear: dto.CouponQuantityPerYear,
		FloatingCouponFlag:    dto.FloatingCouponFlag,
		InitialNominal:        dto.InitialNominal.ToFloat(),
		IssueKind:             dto.IssueKind,
		IssueSize:             dto.IssueSize,
		IssueSizePlan:         dto.IssueSizePlan,
		MaturityDate:          dto.MaturityDate,
		Nominal:               dto.Nominal.ToFloat(),
		PerpetualFlag:         dto.PerpetualFlag,
		PlacementDate:         dto.PlacementDate,
		PlacementPrice:        dto.PlacementPrice.ToFloat(),
		RiskLevel:             dto.RiskLevel.ToString(),
		Sector:                dto.Sector,
		StateRegDate:          dto.StateRegDate,
		SubordinatedFlag:      dto.SubordinatedFlag,
		BondType:              dto.BondType,
	}
}
