package mappers

import (
	"invest-mate/internal/models/domain"
	"invest-mate/internal/models/dto"
	"invest-mate/internal/models/entity"
)

func BondFromDtoMapper(dto dto.Bond) domain.Bond {
	return domain.Bond{
		Figi:                  dto.Figi,
		Ticker:                dto.Ticker,
		PositionUid:           dto.PositionUid,
		ClassCode:             dto.ClassCode,
		Isin:                  dto.Isin,
		Lot:                   dto.Lot,
		Currency:              dto.Currency,
		Klong:                 dto.Klong.ToFloat(),
		Kshort:                dto.Kshort.ToFloat(),
		Dlong:                 dto.Dlong.ToFloat(),
		Dshort:                dto.Dshort.ToFloat(),
		DlongMin:              dto.DlongMin.ToFloat(),
		DshortMin:             dto.DshortMin.ToFloat(),
		Exchange:              dto.Exchange,
		RealExchange:          dto.RealExchange,
		ShortEnabledFlag:      dto.ShortEnabledFlag,
		Name:                  dto.Name,
		CountryOfRiskName:     dto.CountryOfRiskName,
		TradingStatus:         dto.TradingStatus,
		OtcFlag:               dto.OtcFlag,
		BuyAvailableFlag:      dto.BuyAvailableFlag,
		SellAvailableFlag:     dto.SellAvailableFlag,
		MinPriceIncrement:     dto.MinPriceIncrement.ToFloat(),
		ApiTradeAvailableFlag: dto.ApiTradeAvailableFlag,
		Uid:                   dto.Uid,
		AssetUid:              dto.AssetUid,
		ForIisFlag:            dto.ForIisFlag,
		ForQualInvestorFlag:   dto.ForQualInvestorFlag,
		WeekendFlag:           dto.WeekendFlag,
		BlockedTcaFlag:        dto.BlockedTcaFlag,
		LiquidityFlag:         dto.LiquidityFlag,
		First1minCandleDate:   dto.First1minCandleDate,
		First1dayCandleDate:   dto.First1dayCandleDate,
		AciValue:              dto.AciValue.ToFloat(),
		AmortizationFlag:      dto.AmortizationFlag,
		CountryOfRisk:         dto.CountryOfRisk,
		CouponQuantityPerYear: dto.CouponQuantityPerYear,
		FloatingCouponFlag:    dto.FloatingCouponFlag,
		InitialNominal:        dto.InitialNominal.ToFloat(),
		IssueKind:             dto.IssueKind,
		IssueSize:             dto.IssueSize,
		IssueSizePlan:         dto.IssueSizePlan,
		MaturityDate:          dto.MaturityDate,
		Nominal:               dto.Nominal.ToFloat(),
		PerpetualFlag:         dto.PerpetualFlag,
		PlacementDate:         dto.PlacementDate,
		PlacementPrice:        dto.PlacementPrice.ToFloat(),
		RiskLevel:             dto.RiskLevel.ToString(),
		Sector:                dto.Sector,
		StateRegDate:          dto.StateRegDate,
		SubordinatedFlag:      dto.SubordinatedFlag,
		BondType:              dto.BondType,
	}
}

func BondToRepositoryMapper(domain []domain.Bond) []entity.Bond {
	res := make([]entity.Bond, len(domain))
	for i, b := range domain {
		res[i] = entity.Bond{
			Uid:                   b.Uid,
			Figi:                  b.Figi,
			Ticker:                b.Ticker,
			Name:                  b.Name,
			Currency:              b.Currency,
			PositionUid:           b.PositionUid,
			ClassCode:             b.ClassCode,
			Isin:                  b.Isin,
			Lot:                   b.Lot,
			Klong:                 b.Klong,
			Kshort:                b.Kshort,
			Dlong:                 b.Dlong,
			Dshort:                b.Dshort,
			DlongMin:              b.DlongMin,
			DshortMin:             b.DshortMin,
			Exchange:              b.Exchange,
			RealExchange:          b.RealExchange,
			ShortEnabledFlag:      b.ShortEnabledFlag,
			CountryOfRiskName:     b.CountryOfRiskName,
			TradingStatus:         b.TradingStatus,
			OtcFlag:               b.OtcFlag,
			BuyAvailableFlag:      b.BuyAvailableFlag,
			SellAvailableFlag:     b.SellAvailableFlag,
			MinPriceIncrement:     b.MinPriceIncrement,
			ApiTradeAvailableFlag: b.ApiTradeAvailableFlag,
			AssetUid:              b.AssetUid,
			ForIisFlag:            b.ForIisFlag,
			ForQualInvestorFlag:   b.ForQualInvestorFlag,
			WeekendFlag:           b.WeekendFlag,
			BlockedTcaFlag:        b.BlockedTcaFlag,
			LiquidityFlag:         b.LiquidityFlag,
			First1minCandleDate:   b.First1minCandleDate,
			First1dayCandleDate:   b.First1dayCandleDate,
			AciValue:              b.AciValue,
			AmortizationFlag:      b.AmortizationFlag,
			CountryOfRisk:         b.CountryOfRisk,
			CouponQuantityPerYear: b.CouponQuantityPerYear,
			FloatingCouponFlag:    b.FloatingCouponFlag,
			InitialNominal:        b.InitialNominal,
			IssueKind:             b.IssueKind,
			IssueSize:             b.IssueSize,
			IssueSizePlan:         b.IssueSizePlan,
			MaturityDate:          b.MaturityDate,
			Nominal:               b.Nominal,
			PerpetualFlag:         b.PerpetualFlag,
			PlacementDate:         b.PlacementDate,
			PlacementPrice:        b.PlacementPrice,
			RiskLevel:             b.RiskLevel,
			Sector:                b.Sector,
			StateRegDate:          b.StateRegDate,
			SubordinatedFlag:      b.SubordinatedFlag,
			BondType:              b.BondType,
		}
	}

	return res
}
