package dto

type Bond struct {
	Figi                  string     `json:"figi"`
	Ticker                string     `json:"ticker"`
	PositionUid           string     `json:"positionUid"`
	ClassCode             string     `json:"classCode"`
	Isin                  string     `json:"isin"`
	Lot                   int        `json:"lot"`
	Currency              string     `json:"currency"`
	Klong                 Quotation  `json:"klong"`
	Kshort                Quotation  `json:"kshort"`
	Dlong                 Quotation  `json:"dlong"`
	Dshort                Quotation  `json:"dshort"`
	DlongMin              Quotation  `json:"dlongMin"`
	DshortMin             Quotation  `json:"dshortMin"`
	Exchange              string     `json:"exchange"`
	RealExchange          string     `json:"realExchange"`
	ShortEnabledFlag      bool       `json:"shortEnabledFlag"`
	Name                  string     `json:"name"`
	CountryOfRiskName     string     `json:"countryOfRiskName"`
	TradingStatus         string     `json:"tradingStatus"`
	OtcFlag               bool       `json:"otcFlag"`
	BuyAvailableFlag      bool       `json:"buyAvailableFlag"`
	SellAvailableFlag     bool       `json:"sellAvailableFlag"`
	MinPriceIncrement     Quotation  `json:"minPriceIncrement"`
	ApiTradeAvailableFlag bool       `json:"apiTradeAvailableFlag"`
	Uid                   string     `json:"uid"`
	AssetUid              string     `json:"assetUid"`
	ForIisFlag            bool       `json:"forIisFlag"`
	ForQualInvestorFlag   bool       `json:"forQualInvestorFlag"`
	WeekendFlag           bool       `json:"weekendFlag"`
	BlockedTcaFlag        bool       `json:"blockedTcaFlag"`
	LiquidityFlag         bool       `json:"liquidityFlag"`
	First1minCandleDate   string     `json:"first1minCandleDate"`
	First1dayCandleDate   string     `json:"first1dayCandleDate"`
	AciValue              MoneyValue `json:"aciValue"`
	AmortizationFlag      bool       `json:"amortizationFlag"`
	CountryOfRisk         string     `json:"countryOfRisk"`
	CouponQuantityPerYear int        `json:"couponQuantityPerYear"`
	FloatingCouponFlag    bool       `json:"floatingCouponFlag"`
	InitialNominal        MoneyValue `json:"initialNominal"`
	IssueKind             string     `json:"issueKind"`
	IssueSize             string     `json:"issueSize"`
	IssueSizePlan         string     `json:"issueSizePlan"`
	MaturityDate          string     `json:"maturityDate"`
	Nominal               MoneyValue `json:"nominal"`
	PerpetualFlag         bool       `json:"perpetualFlag"`
	PlacementDate         string     `json:"placementDate"`
	PlacementPrice        MoneyValue `json:"placementPrice"`
	RiskLevel             RiskLevel  `json:"riskLevel"`
	Sector                string     `json:"sector"`
	StateRegDate          string     `json:"stateRegDate"`
	SubordinatedFlag      bool       `json:"subordinatedFlag"`
	BondType              string     `json:"bondType"`
}
